### ISSUE TITLE
Collision Checking

### ISSUE THREAD

**Issue by lab596** [kanhaiworld/BasketBallGame#8]
How will we check collisions with the hoop after the ball "goes in"
Currently I am trying to see if the ball touches the rim but I cannot just simply say if the x values of the rim and of the ball are equal cause the chances of those lining up is slim to none as we are referencing one pixel.
If you have a suggestion of how to fix this problem please let me know. 

FYI for the snake game I simply checked if the snake head is out of the field of the GUI, we cannot do that for this.

**Comment by lab596** [comment]
I fix

**Comment by lab596** [comment]
close this

**Comment by kanhaiworld** [comment]
Rohan?!?!?!
